#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF'
Usage: build_release.sh [options] [APP_PATH] [OUTPUT_DMG]

Runs a clean macOS release build:
1) Archives existing dist/ and build/ with timestamps
2) Builds app with PyInstaller (--clean -y macos.spec)
3) Ad-hoc signs all binaries inside the .app bundle (innermost-first order)
4) Packages a compressed drag-and-drop DMG
5) Optionally creates a code-signature-preserving ZIP for web distribution
6) Optionally signs and notarizes the release artifacts

Defaults:
- APP_PATH:   dist/KinoVolume.app
- OUTPUT_DMG: auto-generated by create_dmg.sh

Options:
- --sign       Sign app and DMG using Developer ID Application identity
- --notarize   Notarize DMG with notarytool (implies --sign)
- --staple-app Attempt to staple the app after notarization
- --no-prompt  Fail instead of asking interactively for missing values
- --zip        Create a distribution ZIP that preserves code signatures
               Uses ditto instead of zip so signatures survive unzipping
               Output: dist/KinoVolume-vX.Y.zip

Environment variables:
- PYTHON_BIN
- DEVELOPER_ID_APPLICATION
- NOTARY_PROFILE
- NOTARY_APPLE_ID
- NOTARY_TEAM_ID
- NOTARY_PASSWORD (app-specific password)
EOF
}

prompt_value() {
  local var_name="$1"
  local prompt_text="$2"
  local current_value="$3"
  if [[ -n "$current_value" ]]; then
    printf '%s\n' "$current_value"
    return 0
  fi
  if [[ "$NO_PROMPT" -eq 1 ]]; then
    echo "Missing required value: $var_name"
    exit 1
  fi
  local response=""
  read -r -p "$prompt_text" response
  if [[ -z "$response" ]]; then
    echo "Missing required value: $var_name"
    exit 1
  fi
  printf '%s\n' "$response"
}

prompt_secret() {
  local var_name="$1"
  local prompt_text="$2"
  local current_value="$3"
  if [[ -n "$current_value" ]]; then
    printf '%s\n' "$current_value"
    return 0
  fi
  if [[ "$NO_PROMPT" -eq 1 ]]; then
    echo "Missing required value: $var_name"
    exit 1
  fi
  local response=""
  read -r -s -p "$prompt_text" response
  echo
  if [[ -z "$response" ]]; then
    echo "Missing required value: $var_name"
    exit 1
  fi
  printf '%s\n' "$response"
}

to_abs_path() {
  local path_value="$1"
  if [[ "$path_value" = /* ]]; then
    printf '%s\n' "$path_value"
  else
    printf '%s/%s\n' "$PROJECT_ROOT" "$path_value"
  fi
}

resolve_output_dmg_path() {
  local app_abs="$1"
  local output_arg="$2"
  if [[ -n "$output_arg" ]]; then
    if [[ "$output_arg" = /* ]]; then
      printf '%s\n' "$output_arg"
    else
      printf '%s/%s\n' "$PROJECT_ROOT" "$output_arg"
    fi
    return 0
  fi

  local app_name
  local app_stem
  local version
  app_name="$(basename "$app_abs")"
  app_stem="${app_name%.app}"
  version="$(/usr/libexec/PlistBuddy -c 'Print :CFBundleShortVersionString' "$app_abs/Contents/Info.plist" 2>/dev/null || true)"
  if [[ -z "$version" ]]; then
    version="0.0"
  fi
  printf '%s/dist/%s-v%s.dmg\n' "$PROJECT_ROOT" "${app_stem// /-}" "$version"
}

# ---------------------------------------------------------------------------
# Ad-hoc code signing — thorough, inside-out approach
# ---------------------------------------------------------------------------
# Gatekeeper behavior:
#   - Unsigned binaries + quarantine xattr = "damaged, move to Trash"
#   - Ad-hoc signed + quarantine xattr = "unidentified developer" (bypassable
#     via right-click → Open or Privacy & Security pane)
#   - The key is signing EVERY Mach-O binary inside the bundle, innermost
#     first, so that the outer signature seal covers everything.
#
# WARNING: Do NOT use `codesign --deep` on the .app bundle. It tries to sign
# non-Mach-O items (.dist-info, .py, .txt) as bundles, which produces
# "bundle format unrecognized, invalid, or unsuitable" errors.
# Instead, explicitly iterate over every Mach-O binary (.dylib, .so,
# frameworks, executables) and sign them individually inside-out.
# ---------------------------------------------------------------------------
ad_hoc_sign_app() {
  local app="$1"
  echo "  → Ad-hoc signing: $app"

  local contents="$app/Contents"

  # Helper: strip existing signature then ad-hoc sign a file
  _sign_file() {
    local f="$1"
    codesign --remove-signature "$f" 2>/dev/null || true
    codesign --force --sign - --timestamp=none "$f" 2>/dev/null || echo "    [warn] Could not sign: $f"
  }

  # Helper: strip existing signature then ad-hoc sign a framework bundle
  _sign_framework() {
    local fw="$1"
    codesign --remove-signature "$fw" 2>/dev/null || true
    codesign --force --sign - --timestamp=none "$fw" 2>/dev/null || echo "    [warn] Could not sign: $(basename "$fw")"
  }

  # ---- Step 0: Detect all Mach-O files inside the bundle ----
  # Uses `file` to find Mach-O binaries so we don't miss anything
  echo "    0/6 Discovering all Mach-O binaries …"
  local macho_files=()
  while IFS= read -r -d '' f; do
    macho_files+=("$f")
  done < <(find "$contents" -type f -print0 2>/dev/null | \
    xargs -0 file 2>/dev/null | \
    grep -E 'Mach-O (64-bit|universal)' | \
    cut -d: -f1 | \
    sort -r | \
    tr '\n' '\0' || true)
  echo "      Found ${#macho_files[@]} Mach-O binaries."

  # ---- Step 1: Sign individual Mach-O files innermost first (sorted reverse) ----
  echo "    1/6 Signing all Mach-O binaries (inside-out order) …"
  local signed_count=0
  local total_macho=${#macho_files[@]}
  for f in "${macho_files[@]}"; do
    _sign_file "$f"
    signed_count=$((signed_count + 1))
  done
  echo "      Signed $signed_count/$total_macho binaries."

  # ---- Step 2: Sign Python framework if present ----
  echo "    2/6 Signing Python.framework …"
  local python_fw="$contents/Frameworks/Python.framework"
  if [[ -d "$python_fw" ]]; then
    _sign_framework "$python_fw"
  else
    echo "      Python.framework not found (bundled Python in MacOS/)."
  fi

  # ---- Step 3: Sign Qt frameworks individually ----
  echo "    3/6 Signing Qt frameworks …"
  local qt_lib_dirs=(
    "$contents/Resources/PySide6/Qt/lib"
    "$contents/Frameworks"
  )
  local qt_signed=0
  for qt_dir in "${qt_lib_dirs[@]}"; do
    if [[ -d "$qt_dir" ]]; then
      while IFS= read -r -d '' fw; do
        _sign_framework "$fw"
        qt_signed=$((qt_signed + 1))
      done < <(find "$qt_dir" -name "*.framework" -type d -maxdepth 1 -print0 2>/dev/null || true)
    fi
  done
  echo "      Signed $qt_signed Qt frameworks."

  # ---- Step 4: Also check for .dylib bundles that are directories ----
  echo "    4/6 Signing any .framework/.bundle dirs …"
  while IFS= read -r -d '' bundle_dir; do
    _sign_framework "$bundle_dir"
  done < <(find "$contents" \( -name "*.framework" -o -name "*.bundle" \) -type d -print0 2>/dev/null || true)

  # ---- Step 5: Verify individual binary signatures ----
  echo "    5/5 Verifying individual binary signatures …"
  local verified=0
  local failed=0
  for f in "${macho_files[@]}"; do
    if codesign --verify --verbose=0 "$f" 2>/dev/null; then
      verified=$((verified + 1))
    else
      failed=$((failed + 1))
    fi
  done
  echo "      Verified: $verified/$total_macho, Failed: $failed"

  if [[ "$failed" -gt 0 ]]; then
    echo "  ⚠ $failed binaries could not be verified."
    echo "    This is normal for some pip-packaged .so files with pre-existing"
    echo "    signatures (onnxruntime, opencv). These will still work — macOS"
    echo "    checks each binary individually when loading it."
  fi

  # ---- Summary ----
  echo ""
  echo "  ✓ Ad-hoc signing complete."
  echo "    All Mach-O binaries signed. The .app bundle itself is not sealed"
  echo "    because PyInstaller bundles contain non-Mach-O data files (.py,"
  echo "    .dist-info) that prevent bundle-level sealing. Gatekeeper checks"
  echo "    the individual binary signatures, not the bundle seal."
  echo ""
  echo "    When users open the app, macOS will show:"
  echo "      'KinoVolume.app is from an unidentified developer.'"
  echo "    Users can bypass this via:"
  echo "      - Right-click the app → Open (one time only)"
  echo "      - System Settings → Privacy & Security → Open Anyway"
  echo "    This is the standard Gatekeeper behavior for ad-hoc signed apps."
}

SIGN_RELEASE=0
NOTARIZE_RELEASE=0
STAPLE_APP=0
NO_PROMPT=0
CREATE_ZIP=0

POSITIONAL_ARGS=()
while [[ $# -gt 0 ]]; do
  case "$1" in
    --sign)
      SIGN_RELEASE=1
      shift
      ;;
    --notarize)
      SIGN_RELEASE=1
      NOTARIZE_RELEASE=1
      shift
      ;;
    --staple-app)
      STAPLE_APP=1
      shift
      ;;
    --no-prompt)
      NO_PROMPT=1
      shift
      ;;
    --zip)
      CREATE_ZIP=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    --)
      shift
      while [[ $# -gt 0 ]]; do
        POSITIONAL_ARGS+=("$1")
        shift
      done
      ;;
    -*)
      echo "Unknown option: $1"
      usage
      exit 1
      ;;
    *)
      POSITIONAL_ARGS+=("$1")
      shift
      ;;
  esac
done

APP_PATH="${POSITIONAL_ARGS[0]:-dist/KinoVolume.app}"
OUTPUT_DMG="${POSITIONAL_ARGS[1]:-}"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
PYTHON_BIN="${PYTHON_BIN:-$PROJECT_ROOT/.venv/bin/python}"
DEVELOPER_ID_APPLICATION="${DEVELOPER_ID_APPLICATION:-}"
NOTARY_PROFILE="${NOTARY_PROFILE:-kinovolume-notary}"
NOTARY_APPLE_ID="${NOTARY_APPLE_ID:-}"
NOTARY_TEAM_ID="${NOTARY_TEAM_ID:-}"
NOTARY_PASSWORD="${NOTARY_PASSWORD:-}"

if [[ ! -x "$PYTHON_BIN" ]]; then
  echo "Python executable not found: $PYTHON_BIN"
  echo "Set PYTHON_BIN or create project venv at .venv/bin/python"
  exit 1
fi

cd "$PROJECT_ROOT"

TS="$(date +%Y%m%d_%H%M%S)"
if [[ -d dist ]]; then
  mv dist "dist_preclean_$TS"
fi
if [[ -d build ]]; then
  mv build "build_preclean_$TS"
fi

echo "=== Building with PyInstaller ==="
"$PYTHON_BIN" -m PyInstaller --clean -y macos.spec

APP_PATH_ABS="$(to_abs_path "$APP_PATH")"
if [[ ! -d "$APP_PATH_ABS" ]]; then
  echo "App bundle not found after build: $APP_PATH_ABS"
  exit 1
fi

echo ""
echo "=== Signing ==="
if [[ "$SIGN_RELEASE" -eq 1 ]]; then
  if [[ -z "$DEVELOPER_ID_APPLICATION" && "$NO_PROMPT" -eq 0 ]]; then
    echo "Available code-signing identities:"
    security find-identity -v -p codesigning || true
  fi
  DEVELOPER_ID_APPLICATION="$(prompt_value "DEVELOPER_ID_APPLICATION" "Developer ID Application identity: " "$DEVELOPER_ID_APPLICATION")"

  echo "Signing app with Developer ID: $APP_PATH_ABS"
  codesign --force --deep --options runtime --timestamp --sign "$DEVELOPER_ID_APPLICATION" "$APP_PATH_ABS"
  codesign --verify --deep --strict --verbose=2 "$APP_PATH_ABS"
else
  # PyInstaller 6.x already ad-hoc signs the .app bundle during BUILD.
  # (visible in the log as "Signing the BUNDLE...")
  # The .app bundle and embedded Mach-O binaries are already correctly
  # signed by PyInstaller. We verify but do NOT re-sign — re-signing
  # would strip PyInstaller's valid seal and fail on newer macOS
  # because codesign sees .py files inside the embedded PKG archive.
  echo "Ad-hoc signing: using PyInstaller's built-in signature."
  echo "  PyInstaller 6.x signs the .app bundle during the build."
  echo "  No additional signing needed for ad-hoc distribution."

  # Verify PyInstaller's signature on the .app bundle
  echo "  Verifying PyInstaller's ad-hoc signature …"
  if codesign --verify --verbose=1 "$APP_PATH_ABS" 2>&1; then
    echo "  ✓ PyInstaller ad-hoc signature verified."
  else
    echo "  ⚠ Bundle-level verification had issues (expected for PyInstaller)."
    echo "  Checking individual component signatures …"

    # Check main executable
    MAIN_EXE="$APP_PATH_ABS/Contents/MacOS/KinoVolume"
    if [[ -f "$MAIN_EXE" ]]; then
      echo "  --- Main executable ($MAIN_EXE) ---"
      if codesign --verify --verbose=1 "$MAIN_EXE" 2>&1; then
        echo "  ✓ Main executable is properly signed."
      else
        echo "  ✗ Main executable has NO valid signature!"
        codesign -dvvv "$MAIN_EXE" 2>&1 | head -10 || true
      fi
    fi

    # Check a few dylibs
    echo "  --- Sample dylibs ---"
    SAMPLE_DYLIB="$(find "$APP_PATH_ABS/Contents" -name "libshiboken6*.dylib" -type f 2>/dev/null | head -1)"
    if [[ -n "$SAMPLE_DYLIB" ]]; then
      if codesign --verify --verbose=1 "$SAMPLE_DYLIB" 2>&1; then
        echo "  ✓ Sample dylib is signed."
      else
        echo "  ✗ Sample dylib has NO signature!"
      fi
    fi
  fi

  echo ""
  echo "  When users open the app, macOS will show:"
  echo "    'KinoVolume.app is from an unidentified developer.'"
  echo "  Users can bypass this via:"
  echo "    - Right-click the app → Open (first time only)"
  echo "    - System Settings → Privacy & Security → Open Anyway"
fi

echo ""
echo "=== Creating DMG ==="
if [[ -n "$OUTPUT_DMG" ]]; then
  "$PROJECT_ROOT/packaging/macos/create_dmg.sh" "$APP_PATH_ABS" "$OUTPUT_DMG"
else
  "$PROJECT_ROOT/packaging/macos/create_dmg.sh" "$APP_PATH_ABS"
fi

DMG_PATH_ABS="$(resolve_output_dmg_path "$APP_PATH_ABS" "$OUTPUT_DMG")"
if [[ ! -f "$DMG_PATH_ABS" ]]; then
  DMG_PATH_ABS="$(ls -t "$PROJECT_ROOT"/dist/*.dmg 2>/dev/null | head -1 || true)"
fi
if [[ -z "$DMG_PATH_ABS" || ! -f "$DMG_PATH_ABS" ]]; then
  echo "Could not find the generated DMG file."
  exit 1
fi

if [[ "$SIGN_RELEASE" -eq 1 ]]; then
  echo ""
  echo "=== Signing DMG ==="
  codesign --force --timestamp --sign "$DEVELOPER_ID_APPLICATION" "$DMG_PATH_ABS"
fi

# ---------------------------------------------------------------------------
# Create a code-signature-preserving ZIP for web distribution
# ---------------------------------------------------------------------------
# Regular `zip` strips extended attributes and code signatures.
# `ditto -c -k` preserves them, so the extracted app still has valid ad-hoc
# signatures. Without this, users get "damaged" errors because the unzipped
# app has NO signature at all + quarantine xattr from browser download.
# ---------------------------------------------------------------------------
if [[ "$CREATE_ZIP" -eq 1 ]]; then
  echo ""
  echo "=== Creating distribution ZIP (signature-preserving) ==="
  ZIP_NAME="$(basename "$APP_PATH_ABS")"
  ZIP_STEM="${ZIP_NAME%.app}"
  VERSION_FOR_ZIP="$(/usr/libexec/PlistBuddy -c 'Print :CFBundleShortVersionString' "$APP_PATH_ABS/Contents/Info.plist" 2>/dev/null || echo "0.0")"
  ZIP_OUT="$PROJECT_ROOT/dist/${ZIP_STEM// /-}-v${VERSION_FOR_ZIP}.zip"

  # ditto -c -k creates a PKZip archive that preserves:
  #   - Code signatures (codesign data in __LINKEDIT)
  #   - Extended attributes (important for Finder integration)
  #   - Resource forks (not used here, but good practice)
  #   - Symlinks
  # --sequesterRsrc is not needed on modern macOS but kept for safety
  echo "  Creating: $ZIP_OUT"
  ditto -c -k --keepParent --sequesterRsrc "$APP_PATH_ABS" "$ZIP_OUT"

  echo "  ✓ Distribution ZIP created (code signatures preserved)."
  echo "  Important: distribute THIS zip, not one made with Finder 'Compress'."
  echo "  When users download and unzip, the app will show 'unidentified developer'"
  echo "  but can be opened via right-click → Open."
fi

if [[ "$NOTARIZE_RELEASE" -eq 1 ]]; then
  if ! xcrun notarytool history --keychain-profile "$NOTARY_PROFILE" >/dev/null 2>&1; then
    echo "Notary profile '$NOTARY_PROFILE' not found or unavailable."
    NOTARY_APPLE_ID="$(prompt_value "NOTARY_APPLE_ID" "Apple ID for notarization: " "$NOTARY_APPLE_ID")"
    NOTARY_TEAM_ID="$(prompt_value "NOTARY_TEAM_ID" "Apple Team ID: " "$NOTARY_TEAM_ID")"
    NOTARY_PASSWORD="$(prompt_secret "NOTARY_PASSWORD" "App-specific password: " "$NOTARY_PASSWORD")"
    xcrun notarytool store-credentials "$NOTARY_PROFILE" --apple-id "$NOTARY_APPLE_ID" --team-id "$NOTARY_TEAM_ID" --password "$NOTARY_PASSWORD"
  fi

  echo ""
  echo "=== Notarizing ==="
  echo "Submitting DMG for notarization: $DMG_PATH_ABS"
  xcrun notarytool submit "$DMG_PATH_ABS" --keychain-profile "$NOTARY_PROFILE" --wait

  echo "Stapling DMG ticket"
  xcrun stapler staple "$DMG_PATH_ABS"

  if [[ "$STAPLE_APP" -eq 1 ]]; then
    echo "Stapling app ticket"
    xcrun stapler staple "$APP_PATH_ABS" || true
  fi

  echo "Gatekeeper check for DMG"
  spctl -a -vvv --type open "$DMG_PATH_ABS" || true
fi

echo ""
echo "══════════════════════════════════════════════════════════════"
echo "Release build complete."
echo ""
echo "App:  $APP_PATH_ABS"
echo "DMG:  $DMG_PATH_ABS"
if [[ "$CREATE_ZIP" -eq 1 ]]; then
  echo "ZIP:  ${ZIP_OUT:-not created}"
fi
echo ""
if [[ "$SIGN_RELEASE" -eq 0 ]]; then
  echo "Distribution notes (ad-hoc signed):"
  echo "  • DMG: Best option. Users double-click DMG, drag app to"
  echo "         /Applications, then right-click → Open the first time."
  if [[ "$CREATE_ZIP" -eq 1 ]]; then
    echo "  • ZIP: Use for web downloads. Created with ditto to preserve"
    echo "         code signatures. After unzipping, right-click → Open."
  fi
  echo "  • Do NOT zip the .app with Finder 'Compress' or regular zip —"
  echo "    that strips code signatures and causes 'damaged' errors."
  echo "  • The 'sudo xattr -cr /path/to/KinoVolume.app' workaround"
  echo "    should no longer be necessary with this build."
fi
echo "══════════════════════════════════════════════════════════════"
