#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF'
Usage: build_release.sh [options] [APP_PATH] [OUTPUT_DMG]

Runs a clean macOS release build:
1) Archives existing dist/ and build/ with timestamps
2) Builds app with PyInstaller (--clean -y macos.spec)
3) Packages a compressed drag-and-drop DMG
4) Optionally signs and notarizes the release artifacts

Defaults:
- APP_PATH:   dist/KinoVolume.app
- OUTPUT_DMG: auto-generated by create_dmg.sh

Options:
- --sign       Sign app and DMG using Developer ID Application identity
- --notarize   Notarize DMG with notarytool (implies --sign)
- --staple-app Attempt to staple the app after notarization
- --no-prompt  Fail instead of asking interactively for missing values

Environment variables:
- PYTHON_BIN
- DEVELOPER_ID_APPLICATION
- NOTARY_PROFILE
- NOTARY_APPLE_ID
- NOTARY_TEAM_ID
- NOTARY_PASSWORD (app-specific password)
EOF
}

prompt_value() {
  local var_name="$1"
  local prompt_text="$2"
  local current_value="$3"
  if [[ -n "$current_value" ]]; then
    printf '%s\n' "$current_value"
    return 0
  fi
  if [[ "$NO_PROMPT" -eq 1 ]]; then
    echo "Missing required value: $var_name"
    exit 1
  fi
  local response=""
  read -r -p "$prompt_text" response
  if [[ -z "$response" ]]; then
    echo "Missing required value: $var_name"
    exit 1
  fi
  printf '%s\n' "$response"
}

prompt_secret() {
  local var_name="$1"
  local prompt_text="$2"
  local current_value="$3"
  if [[ -n "$current_value" ]]; then
    printf '%s\n' "$current_value"
    return 0
  fi
  if [[ "$NO_PROMPT" -eq 1 ]]; then
    echo "Missing required value: $var_name"
    exit 1
  fi
  local response=""
  read -r -s -p "$prompt_text" response
  echo
  if [[ -z "$response" ]]; then
    echo "Missing required value: $var_name"
    exit 1
  fi
  printf '%s\n' "$response"
}

to_abs_path() {
  local path_value="$1"
  if [[ "$path_value" = /* ]]; then
    printf '%s\n' "$path_value"
  else
    printf '%s/%s\n' "$PROJECT_ROOT" "$path_value"
  fi
}

resolve_output_dmg_path() {
  local app_abs="$1"
  local output_arg="$2"
  if [[ -n "$output_arg" ]]; then
    if [[ "$output_arg" = /* ]]; then
      printf '%s\n' "$output_arg"
    else
      printf '%s/%s\n' "$PROJECT_ROOT" "$output_arg"
    fi
    return 0
  fi

  local app_name
  local app_stem
  local version
  app_name="$(basename "$app_abs")"
  app_stem="${app_name%.app}"
  version="$(/usr/libexec/PlistBuddy -c 'Print :CFBundleShortVersionString' "$app_abs/Contents/Info.plist" 2>/dev/null || true)"
  if [[ -z "$version" ]]; then
    version="0.0"
  fi
  printf '%s/dist/%s-v%s.dmg\n' "$PROJECT_ROOT" "${app_stem// /-}" "$version"
}

SIGN_RELEASE=0
NOTARIZE_RELEASE=0
STAPLE_APP=0
NO_PROMPT=0

POSITIONAL_ARGS=()
while [[ $# -gt 0 ]]; do
  case "$1" in
    --sign)
      SIGN_RELEASE=1
      shift
      ;;
    --notarize)
      SIGN_RELEASE=1
      NOTARIZE_RELEASE=1
      shift
      ;;
    --staple-app)
      STAPLE_APP=1
      shift
      ;;
    --no-prompt)
      NO_PROMPT=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    --)
      shift
      while [[ $# -gt 0 ]]; do
        POSITIONAL_ARGS+=("$1")
        shift
      done
      ;;
    -*)
      echo "Unknown option: $1"
      usage
      exit 1
      ;;
    *)
      POSITIONAL_ARGS+=("$1")
      shift
      ;;
  esac
done

APP_PATH="${POSITIONAL_ARGS[0]:-dist/KinoVolume.app}"
OUTPUT_DMG="${POSITIONAL_ARGS[1]:-}"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
PYTHON_BIN="${PYTHON_BIN:-$PROJECT_ROOT/.venv/bin/python}"
DEVELOPER_ID_APPLICATION="${DEVELOPER_ID_APPLICATION:-}"
NOTARY_PROFILE="${NOTARY_PROFILE:-kinovolume-notary}"
NOTARY_APPLE_ID="${NOTARY_APPLE_ID:-}"
NOTARY_TEAM_ID="${NOTARY_TEAM_ID:-}"
NOTARY_PASSWORD="${NOTARY_PASSWORD:-}"

if [[ ! -x "$PYTHON_BIN" ]]; then
  echo "Python executable not found: $PYTHON_BIN"
  echo "Set PYTHON_BIN or create project venv at .venv/bin/python"
  exit 1
fi

cd "$PROJECT_ROOT"

TS="$(date +%Y%m%d_%H%M%S)"
if [[ -d dist ]]; then
  mv dist "dist_preclean_$TS"
fi
if [[ -d build ]]; then
  mv build "build_preclean_$TS"
fi

"$PYTHON_BIN" -m PyInstaller --clean -y macos.spec

APP_PATH_ABS="$(to_abs_path "$APP_PATH")"
if [[ ! -d "$APP_PATH_ABS" ]]; then
  echo "App bundle not found after build: $APP_PATH_ABS"
  exit 1
fi

if [[ "$SIGN_RELEASE" -eq 1 ]]; then
  if [[ -z "$DEVELOPER_ID_APPLICATION" && "$NO_PROMPT" -eq 0 ]]; then
    echo "Available code-signing identities:"
    security find-identity -v -p codesigning || true
  fi
  DEVELOPER_ID_APPLICATION="$(prompt_value "DEVELOPER_ID_APPLICATION" "Developer ID Application identity: " "$DEVELOPER_ID_APPLICATION")"

  echo "Signing app with Developer ID: $APP_PATH_ABS"
  codesign --force --deep --options runtime --timestamp --sign "$DEVELOPER_ID_APPLICATION" "$APP_PATH_ABS"
  codesign --verify --deep --strict --verbose=2 "$APP_PATH_ABS"
else
  # Ad-hoc signing: makes the app usable for users without an Apple Developer account.
  # After ad-hoc signing, macOS will show "unidentified developer" but will allow
  # right-click → Open (or System Settings → Privacy & Security → Open Anyway).
  # Without this, the app shows "damaged, move to trash" with no bypass option.
  echo "Ad-hoc signing (no Developer ID needed) …"

  # 1 — Sign every dylib / .so / framework inside the bundle (innermost first)
  while IFS= read -r -d '' f; do
    codesign --force --deep -s - "$f" 2>/dev/null || true
  done < <(find "$APP_PATH_ABS/Contents" \
    \( -name "*.dylib" -o -name "*.so" -o -name "Python" \) \
    -type f -print0 2>/dev/null)

  # 2 — Sign Qt frameworks individually
  QT_FW_DIR="$APP_PATH_ABS/Contents/Resources/PySide6/Qt/lib"
  if [[ -d "$QT_FW_DIR" ]]; then
    while IFS= read -r -d '' fw; do
      codesign --force --deep -s - "$fw" 2>/dev/null || true
    done < <(find "$QT_FW_DIR" -name "*.framework" -type d -maxdepth 1 -print0 2>/dev/null)
  fi

  # 3 — Sign the main executable
  MACOS_DIR="$APP_PATH_ABS/Contents/MacOS"
  if [[ -d "$MACOS_DIR" ]]; then
    while IFS= read -r -d '' exe; do
      codesign --force --deep -s - "$exe" 2>/dev/null || true
    done < <(find "$MACOS_DIR" -type f -perm +111 -print0 2>/dev/null)
  fi

  # 4 — Sign the .app bundle itself
  codesign --force --deep -s - "$APP_PATH_ABS"

  echo "  Ad-hoc signing complete."
  echo "  Users will need to right-click → Open the first time (or approve in"
  echo "  System Settings → Privacy & Security)."
fi

if [[ -n "$OUTPUT_DMG" ]]; then
  "$PROJECT_ROOT/packaging/macos/create_dmg.sh" "$APP_PATH_ABS" "$OUTPUT_DMG"
else
  "$PROJECT_ROOT/packaging/macos/create_dmg.sh" "$APP_PATH_ABS"
fi

DMG_PATH_ABS="$(resolve_output_dmg_path "$APP_PATH_ABS" "$OUTPUT_DMG")"
if [[ ! -f "$DMG_PATH_ABS" ]]; then
  DMG_PATH_ABS="$(ls -t "$PROJECT_ROOT"/dist/*.dmg 2>/dev/null | head -1 || true)"
fi
if [[ -z "$DMG_PATH_ABS" || ! -f "$DMG_PATH_ABS" ]]; then
  echo "Could not find the generated DMG file."
  exit 1
fi

if [[ "$SIGN_RELEASE" -eq 1 ]]; then
  echo "Signing DMG: $DMG_PATH_ABS"
  codesign --force --timestamp --sign "$DEVELOPER_ID_APPLICATION" "$DMG_PATH_ABS"
fi

if [[ "$NOTARIZE_RELEASE" -eq 1 ]]; then
  if ! xcrun notarytool history --keychain-profile "$NOTARY_PROFILE" >/dev/null 2>&1; then
    echo "Notary profile '$NOTARY_PROFILE' not found or unavailable."
    NOTARY_APPLE_ID="$(prompt_value "NOTARY_APPLE_ID" "Apple ID for notarization: " "$NOTARY_APPLE_ID")"
    NOTARY_TEAM_ID="$(prompt_value "NOTARY_TEAM_ID" "Apple Team ID: " "$NOTARY_TEAM_ID")"
    NOTARY_PASSWORD="$(prompt_secret "NOTARY_PASSWORD" "App-specific password: " "$NOTARY_PASSWORD")"
    xcrun notarytool store-credentials "$NOTARY_PROFILE" --apple-id "$NOTARY_APPLE_ID" --team-id "$NOTARY_TEAM_ID" --password "$NOTARY_PASSWORD"
  fi

  echo "Submitting DMG for notarization: $DMG_PATH_ABS"
  xcrun notarytool submit "$DMG_PATH_ABS" --keychain-profile "$NOTARY_PROFILE" --wait

  echo "Stapling DMG ticket"
  xcrun stapler staple "$DMG_PATH_ABS"

  if [[ "$STAPLE_APP" -eq 1 ]]; then
    echo "Stapling app ticket"
    xcrun stapler staple "$APP_PATH_ABS" || true
  fi

  echo "Gatekeeper check for DMG"
  spctl -a -vvv --type open "$DMG_PATH_ABS" || true
fi

echo "Release build complete."
echo "App: $APP_PATH_ABS"
echo "DMG: $DMG_PATH_ABS"
